CREATE DATABASE users_data;

CREATE TABLE IF NOT EXISTS users(
    "id" BIGSERIAL PRIMARY KEY,
    "name" CHARACTER(20) NOT NULL,
    "email" CHARACTER(100) UNIQUE NOT NULL,
    "password" CHARACTER(120) NOT NULL,
    "admin" BOOLEAN DEFAULT FALSE,
    "active" BOOLEAN DEFAULT TRUE,    
);